// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { resolve } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";

// Get the directory of this file
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Load environment variables from .env files in workspace root (2 levels up)
const workspaceRoot = resolve(__dirname, "../..");
import dotenv from "dotenv";
dotenv.config({ path: resolve(workspaceRoot, ".env") });
dotenv.config({ path: resolve(workspaceRoot, ".env") });

const postgresUrl = process.env.POSTGRES_URL || process.env.DATABASE_URL;

if (!postgresUrl) {
  throw new Error(
    "POSTGRES_URL or DATABASE_URL environment variable is not set. " +
      "Please ensure it is set in your .env or .env file."
  );
}

export default {
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "./prisma/migrations",
  },
  datasource: {
    url: postgresUrl,
  },
};
