import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/server/preferences.ts',
    'src/types/preferences.ts',
    'src/payments/stripe.ts',
    'src/payments/subscription.ts',
    'src/auth/index.ts',
    'src/auth/users.ts',
    'src/email/index.ts',
    'src/sanity/index.ts',
    'src/sanity/client-utils.ts',
  ],
  format: ['cjs', 'esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    '@auth0/nextjs-auth0',
    '@tanstack/react-table',
    'server-only',
    'clsx',
    'tailwind-merge',
    'next',
    'next/script',
    'next/link',
    'next/navigation',
    'next/headers',
    'next-sanity',
    '@sanity/image-url',
  ],
  outDir: 'dist',
});
